'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	tn=n(n+1)/2 1, 3, 6, 10, 15, ...	  	 	
Pentagonal	 	    pn=n(3n−1)/2 1, 5, 12, 22, 35, ...   	 	
Hexagonal	 	  	 hn=n(2n−1) 1, 6, 15, 28, 45, ...
It can be verified that   t285 = p165 = h143 = 40755 .

Find the next triangle number that is also pentagonal and hexagonal.
'''
def is_triangle(n: int) -> bool:
    """Check if n is a triangle number."""
    x = int(((-1 + (1 + 8 * n) ** 0.5) / 2))
    return x * (x + 1) // 2 == n
def is_pentagonal(n: int) -> bool:
    """Check if n is a pentagonal number."""
    x = int((1 + (1 + 24 * n) ** 0.5) / 6)
    return x * (3 * x - 1) // 2 == n
def is_hexagonal(n: int) -> bool:
    """Check if n is a hexagonal number."""
    x = int((1 + (1 + 8 * n) ** 0.5) / 4)
    return x * (2 * x - 1) == n
def find_next_common_number() -> int:
    """Find the next triangle number that is also pentagonal and hexagonal."""
    n = 286  # Start from the next triangle number after 285
    while True:
        triangle_num = n * (n + 1) // 2
        if is_pentagonal(triangle_num) and is_hexagonal(triangle_num):
            return triangle_num
        n += 1  
if __name__ == "__main__":
    result = find_next_common_number()
    print(result)