"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle 
number would be  1+2+3+4+5+6+7 = 28. The first ten terms would be:
1,3,6,10,15,21,28,36,45,55,...
Let us list the factors of the first seven triangle numbers:
1:1
3:1,3
6:1,2,3,6
10:1,2,5,10
15:1,3,5,15
21:1,3,7,21
28:1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

def count_divisors(n: int) -> int:
    """
    Count the number of divisors of a given integer n.
    """
    count = 0
    for i in range(1, int(n**0.5) + 1):
        if n % i == 0:
            count += 2  # i and n//i are both divisors
    if int(n**0.5)**2 == n:
        count -= 1  # Correct for a perfect square
    return count

def first_triangle_with_divisors_over(limit: int) -> int:
    """
    Find the first triangle number that has more than 'limit' divisors.
    """
    n = 1
    triangle_number = 0
    while True:
        triangle_number += n  # Generate the nth triangle number
        if count_divisors(triangle_number) > limit:
            return triangle_number
        n += 1

if __name__ == "__main__":
    result = first_triangle_with_divisors_over(500)
    print(result)

# Output: 76576500