"""
Problem 2: Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def sum_of_even_fibonacci(n: int) -> int:
    """
    Calculate the sum of even-valued Fibonacci terms not exceeding n.

    :param n: Upper limit (inclusive)
    :return: Sum of even Fibonacci terms ≤ n
    """
    a, b = 1, 2
    total_sum = 0

    while a <= n:
        if a % 2 == 0:
            total_sum += a
        a, b = b, a + b

    return total_sum


# =================================
# Main Execution
# =================================
if __name__ == "__main__":
    result = sum_of_even_fibonacci(4_000_000)
    print(
        "Sum of even-valued terms in the Fibonacci sequence "
        "whose values do not exceed four million:",
        result
    )

# Expected Output:
# 4613732