'''
Pentagonal numbers are generated by the formula, p_n = n(3n - 1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145

It can be seen that  p4+p7=22+70=92= p8 . However, their difference, 70-22=48 , is not pentagonal.

Find the pair of pentagonal numbers,pj  and pk , for which their sum and difference are pentagonal and  d=|pj-pk|  is minimised; what is the value of ?
'''
def is_pentagonal(num: int) -> bool:
    """Check if a number is pentagonal."""
    n = (1 + (1 + 24 * num) ** 0.5) / 6
    return n.is_integer()
def find_min_pentagonal_difference() -> int:
    """Find the minimum difference of pentagonal numbers whose sum and difference are also pentagonal."""
    pentagonal_numbers = []
    n = 1
    while True:
        p_n = n * (3 * n - 1) // 2
        pentagonal_numbers.append(p_n)
        for j in range(len(pentagonal_numbers) - 1):
            pj = pentagonal_numbers[j]
            pk = p_n
            if is_pentagonal(pj + pk) and is_pentagonal(abs(pk - pj)):
                return abs(pk - pj)
        n += 1
if __name__ == "__main__":
    result = find_min_pentagonal_difference()
    print(result)